config/routes.rb
Degradation::Application.routes.draw do
  get "home/index"
  root :to => 'home#index'

  resources :books
  resources :authors
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books, :dependent => :destroy

	def isCreateAuthor?
		return true if self.renewal.nil? 
		return true if self.renewal < DateTime.now 
		return false 	
	end 


end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author

	def axis_text 
		"#{self.title} - #{self.year}"
	end

	def showrating
		r = self.rating
		return 0 if r.nil? 
		self.rating.to_f / 100
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
load "degradation_goodreads.rb"

class HomeController < ApplicationController
  def searchTable (searchlist)
  	data_table = GoogleVisualr::DataTable.new

  	data_table.new_column('string', 'Book Title' ) 
	data_table.new_column('number', 'Rating') 

	searchlist.each do |book|
		data_table.add_row([book.axis_text,book.showrating])
	end

	if !searchlist.blank? 
		every = searchlist.count / 10
	else
		every = 0
	end

	chartarea = {left:30,top:0,width:"100%",height:"100%"}
	hAxis = {slantedTextAngle: 90}
	option = {axisTitlesPosition: "none", 
		fontSize: 12, 
		chartArea: chartarea, 
		hAxis: hAxis, 
		width: 630, height: 300, 
		title: 'Degradation', curveType: 'function' }
	result = GoogleVisualr::Interactive::LineChart.new(data_table, option)
  end

  def index
  	sSearch = params[:search]
  	if !sSearch.blank?
  		searcher = Degradation_goodreads.new
  		@search = searcher.book_list(sSearch)
  		@author = searcher.current_author
  		@chart = searchTable(@search)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :renewal %><br />
    <%= f.datetime_select :renewal %>
  </div>
  <div class="field">
    <%= f.label :didyoumean %><br />
    <%= f.text_field :didyoumean %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Renewal</th>
    <th>Didyoumean</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= author.renewal %></td>
    <td><%= author.didyoumean %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>

<p>
  <b>Renewal:</b>
  <%= @author.renewal %>
</p>

<p>
  <b>Didyoumean:</b>
  <%= @author.didyoumean %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Year</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Isbn</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.author %></td>
    <td><%= book.year %></td>
    <td><%= book.title %></td>
    <td><%= book.rating %></td>
    <td><%= book.isbn %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Year:</b>
  <%= @book.year %>
</p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Rating:</b>
  <%= @book.rating %>
</p>

<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<% content_for(:head) do %>
	<script src='http://www.google.com/jsapi'></script>
<%end%>

<div class="container">

  <!-- Main hero unit for a primary marketing message or call to action -->
  <div class="hero-unit">
	<h1>degradation (v0.2)</h1>
	<p>Being an experiment to see how the percieved quality of an author's work degrades the longer they write for. Try typing in an authors name</p>

	<%=form_tag root_path, :method => 'get' do %>
	  <hr>
	  <p>
	    <%= text_field_tag :search, params[:search],  :class=>"input-large search-query"  %>
	    <%= submit_tag "Search", :name => nil, :class=>"btn btn-primary btn-large"  %>
	  </p>

	  <%if !@author.nil? and !@author.didyoumean.nil? and (@author.didyoumean.downcase!=params[:search].downcase) %>
		  <p><%=link_to "Did you mean #{@author.didyoumean}?", root_path(:search=>@author.didyoumean)%>
	   <%end%>
	<% end %>

	<%if !@search.nil?%>
		<div id="chart_div"></div>

		<div id='chart'></div>

		<%= render_chart(@chart, 'chart') %>
		
	<%end%>
</div>

<div class="footer">
<p><span class="label label-success">Sidenote</span>: Turns out I was wrong as a wrong thing. It appears that the quality of work of most authors seems to be pretty constant. Of course, I'm not a statatician, so these graphs are pretty meaningless to me.</p>

<p><span class="label label-success">Technologies</span>: So, we're using 
  Rails 3.2, 
  The <%=link_to "Goodreads API", "http://www.goodreads.com/"%>, 
  Google Charts, 
  Twitter Bootstrap CSS and 
  AWS.</p>

<p><span class="label label-error">Bugfixes</span>: Weirdness could occur if goodreads api reported different results total to actual results returned.</p>

<p>Written By <%=link_to "Sean Bamforth", "http://theguru.co.uk/"%>.</p>

</div>

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Degradation</title>
  <%= stylesheet_link_tag    "application"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-366025-6']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

</head>
<body>

<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">degradation</a>
        </div>
      </div>
    </div>

    <div class="container">

		<header class="jumbotron masthead">
		  <div class="inner">
			<%= yield %>
		  </div>
		</div>
	</div>



</body>
</html>